language: node_js

node_js:
- node

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: deploy_frontend
      script: ./deploy/frontend.sh
    - stage: deploy_functions
      script: ./deploy/functions.sh